exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('answers').del()
    .then(function () {
      // Inserts seed entries
      return knex('answers').insert([
        {id: 1, questions_Id: 1, response: '106', correct: 'no', description: '...nope.'},
        {id: 2, questions_Id: 1, response: '125', correct: 'yes', description: 'woohoo!'},
        {id: 3, questions_Id: 1, response: '83', correct: 'no', description: 'nice try.'},
        {id: 4, questions_Id: 1, response: '117', correct: 'no', description: 'getting close, but nah.'},
        {id: 5, questions_Id: 2, response: 'Yup', correct: 'yes', description: 'Good thing I was alone, because I am not a good singer.'},
        {id: 6, questions_Id: 2, response: 'Not a chance', correct: 'no', description: 'If you are riding with me, you probably wish I did not sing...'},
        {id: 7, questions_Id: 3, response: 'Jelly Bellies', correct: 'no', description: 'had to resort to these once, but not a go to.'},
        {id: 8, questions_Id: 3, response: 'Peanut Butter Sandwiches', correct: 'yes', description: 'Yup, peanut butter is my JAM...just mising jam. And if I was real lucky I could throw in a banana too!'},
        {id: 9, questions_Id: 3, response: 'Trail Mix', correct: 'no', description: 'I am addicted to trail-mix, so I do not buy it. It would not last long enough.'},
        {id: 10, questions_Id: 3, response: 'Granola Bars', correct: 'no', description: 'A good guess, but nope.'},
        {id: 11, questions_Id: 4, response: '7', correct: 'no', description: '7 peices of roadkill seems like a lot does it not?.'},
        {id: 12, questions_Id: 4, response: '16', correct: 'no', description: 'Okay, wow that is a lot of dead animals. But not the right answer.'},
        {id: 13, questions_Id: 4, response: '4', correct: 'no', description: 'I wish it was this low.'},
        {id: 14, questions_Id: 4, response: '33', correct: 'yes', description: '33!? That is a huge number!!!...but sadly you are correct. I have never seen so much roadkill in my life! Pretty sad.'},
        {id: 15, questions_Id: 5, response: 'Doritos, Snickers, and Coke', correct: 'yes', description: 'Yup, this stuff is locket rocket fuel when you got long drives ahead of you.'},
        {id: 16, questions_Id: 5, response: 'canned pasta, nuts, Red Bull', correct: 'no', description: 'I did have a lot of cold canned pasta, but hard to eat while driving.'},
        {id: 17, questions_Id: 5, response: 'Doritos, Doritos, and Doritos', correct: 'no', description: 'This sounds like a dream...just missing pizza'},
        {id: 18, questions_Id: 5, response: 'Big Mac, Quarter Pounder, fries and a Coke', correct: 'no', description: 'Psh, I do not eat McDonalds, I am being healthy...'},
        {id: 19, questions_Id: 6, response: '/images/answers/map_correct.png', correct: 'yes', description: 'Yay, you got it!'},
        {id: 20, questions_Id: 6, response: '/images/answers/map_wrong1.png', correct: 'no', description: 'Not quite.'},
        {id: 21, questions_Id: 6, response: '/images/answers/map_wrong2.png', correct: 'no', description: 'Nope.'},
        {id: 22, questions_Id: 6, response: '/images/answers/map_wrong3.png', correct: 'no', description: 'You are not correct.'},
        {id: 23, questions_Id: 7, response: '2625 km', correct: 'yes', description: 'Nailed it!'},
        {id: 24, questions_Id: 7, response: '363,104 km', correct: 'no', description: '...That is actually like driving to the moon.'},
        {id: 25, questions_Id: 7, response: '15,761 km', correct: 'no', description: 'New Zealand is not that small'},
        {id: 26, questions_Id: 7, response: '200 km', correct: 'no', description: 'Nadda'},
        {id: 27, questions_Id: 8, response: 'drive to Milford Sounds', correct: 'yes', description: 'This was by far the coolest drive. I stopped practically every 10 min to get out and look at the views.'},
        {id: 28, questions_Id: 8, response: 'Arthurs Pass', correct: 'no', description: 'This was an awesome drive, but is nothing compared to something else on the list.'},
        {id: 29, questions_Id: 8, response: 'Tongariro National Park', correct: 'no', description: 'Pretty mindblowing to see the volcanos pop out of the flat lands, but not epic enough.'},
        {id: 30, questions_Id: 8, response: 'West Coast', correct: 'no', description: 'Very Jurassic Park like, but still not as good as something else.'},
        {id: 31, questions_Id: 9, response: '0, I am obviously to cool to listen to Beibs', correct: 'no', description: 'Thanks, but no I am not that cool.'},
        {id: 32, questions_Id: 9, response: '10, I am a BELIEBER!', correct: 'no', description: 'Not quiet a Belieber either. But he has some cool stuff.'},
        {id: 33, questions_Id: 9, response: '3', correct: 'yes', description: 'And I know all (or at least most) of the words.'},
        {id: 34, questions_Id: 9, response: '5', correct: 'no', description: 'Solid guess'},
        {id: 35, questions_Id: 10, response: '5', correct: 'no', description: 'No...Is it weird that I would keep track of something like this?'},
        {id: 36, questions_Id: 10, response: '0', correct: 'yes', description: 'When you are driving hours on end. There is no point in pressing skip'},
        {id: 37, questions_Id: 10, response: '12', correct: 'no', description: '12 IS divisble by 2 but NOT the amount of skips.'},
        {id: 38, questions_Id: 10, response: '9', correct: 'no', description: '9 is NOT divibisble by 2 and is NOT the amount of skips'},
        {id: 39, questions_Id: 11, response: '0', correct: 'no', description: 'Correct. Responsibility and safety is COOL!'},
        {id: 40, questions_Id: 11, response: '1', correct: 'no', description: 'You must think I am a rebel.'},
        {id: 41, questions_Id: 11, response: '2', correct: 'no', description: 'I sure diiiid...not get 2 speeding tickets.'},
        {id: 42, questions_Id: 11, response: '10', correct: 'no', description: 'Woah! You must think I am crazy!'},
        {id: 43, questions_Id: 12, response: '131', correct: 'no', description: 'Nah'},
        {id: 44, questions_Id: 12, response: '984', correct: 'no', description: 'My tourist level is not quite at expert'},
        {id: 45, questions_Id: 12, response: '676', correct: 'yes', description: 'Yup...I went a little nuts on the photo taking'},
        {id: 46, questions_Id: 12, response: '333', correct: 'no', description: 'three three three, no no no'},
        {id: 47, questions_Id: 13, response: '1031', correct: 'no', description: 'This is a larger number then the choices given for total number of pictures...sooooo nah'},
        {id: 48, questions_Id: 13, response: '113', correct: 'yes', description: 'Yeah budday! I probably took more selifes in these two weeks then I have in my entire life'},
        {id: 49, questions_Id: 13, response: '42', correct: 'no', description: 'It is the answer to life, but not to my selfies'},
        {id: 50, questions_Id: 13, response: '117', correct: 'no', description: 'Master Cheif, Halo, wicked game, but not correct.'},
        {id: 51, questions_Id: 14, response: '10.3 km', correct: 'no', description: 'I am not that soft. Cmon!'},
        {id: 52, questions_Id: 14, response: '50.5 km', correct: 'no', description: 'I wish I was cool enough to do something big like that.'},
        {id: 53, questions_Id: 14, response: '69.69 km', correct: 'no', description: 'Lawls, but no.'},
        {id: 54, questions_Id: 14, response: '20.69 km', correct: 'yes', description: 'Yup, Tongariro Crossing was my biggest day.'},
        {id: 55, questions_Id: 15, response: '114.3 km', correct: 'yes', description: 'Yehaw! I did some adventuring and it was great!.'},
        {id: 56, questions_Id: 15, response: '133.23 km', correct: 'no', description: 'Solid effort, young padawan.'},
        {id: 57, questions_Id: 15, response: '220.2 km', correct: 'no', description: 'Nope.'},
        {id: 58, questions_Id: 15, response: '69.69 km', correct: 'no', description: 'Lawls again. I wish I could give you bonus points if you picked this twice.'},
        {id: 59, questions_Id: 16, response: '10,235 m', correct: 'no', description: 'Nah, again not quite that bad ass.'},
        {id: 60, questions_Id: 16, response: '6969 m', correct: 'no', description: 'Lawls again. If this is third time you have done this. Mad props, I like you.'},
        {id: 61, questions_Id: 16, response: '8770 m', correct: 'yes', description: 'Correct! Average 1000 m per day of trekking. Not bad at all.'},
        {id: 62, questions_Id: 16, response: '12,127 m', correct: 'no', description: 'Nope, not that hard core.'},
        {id: 63, questions_Id: 17, response: '1879 m', correct: 'yes', description: 'Yup, Only because I did two treks this day. Queenstown Hill and Ben Lommond.'},
        {id: 64, questions_Id: 17, response: '1760 m', correct: 'no', description: 'Solid guess. This was Roys Peak, to Mount Alpha'},
        {id: 65, questions_Id: 17, response: '1529 m', correct: 'no', description: 'Surpirisingly the Tongariro Crossing does not have a tone of elevation'},
        {id: 66, questions_Id: 17, response: '1060 m', correct: 'no', description: 'Nope. This was the gain on Mount Fox, and it was definitely the hardest. > 1000 m of elevation in < 3 km!'},
        {id: 67, questions_Id: 18, response: 'Roys Peak to Mount Alpha', correct: 'yes', description: 'The initial hike up Roys peak is not all that great. But the veiws are amazing, then running the ridge to Mount Alpha where I had the mountain to myself made for a perfect day.'},
        {id: 68, questions_Id: 18, response: 'Mount Fox', correct: 'no', description: 'This was a close second. Super gnarly terrain. Basically had to rock climb, and use roots to make it to the top. But I was completely socked in by fog at the top.'},
        {id: 69, questions_Id: 18, response: 'Tongariro Crossing', correct: 'no', description: 'I wish this was it! The conditions were super rough, crazy wind, crazy cold, and no visibility. Made for quite the adventure but I did not see anything. Will have to make my way back some day'},
        {id: 70, questions_Id: 18, response: 'Ben Lommond', correct: 'no', description: 'Nah. Great trek, on Queenstown doorstep, just not as good as the others.'},
        {id: 71, questions_Id: 19, response: 'Leaves', correct: 'no', description: 'I wish there were leaves around, but sadly none were to be found.'},
        {id: 72, questions_Id: 19, response: 'Pinecone', correct: 'no', description: 'Ouch! No! I do not think I would ever resort to that.'},
        {id: 73, questions_Id: 19, response: 'Business card', correct: 'yes', description: 'Yeah...can not recommend it, but there was nothing else!'},
        {id: 74, questions_Id: 19, response: 'A sock', correct: 'no', description: 'Not me. But I no a guy who sacrifced a sock for this purpose.'},
        {id: 75, questions_Id: 20, response: 'Not letting anyone know where I was going', correct: 'no', description: 'Nope. When I could not reach my parents with data, or text a friend. I would write a note and leave it on dashboard of my car "I am on TRAIL alone, if not back by TIME send help" So I think that did the job.'},
        {id: 76, questions_Id: 20, response: 'Not bringing a map', correct: 'no', description: 'No. All the trails I was on were well marked, so no need for a map.'},
        {id: 77, questions_Id: 20, response: 'Hiking with only 500 ml of water and a pack of Jelly Bellies', correct: 'yes', description: 'Yup. That is all I had. No jacket, no supplies, no nothing. But I made it.'},
        {id: 78, questions_Id: 20, response: 'Free climbing a 50 m cliff', correct: 'no', description: 'Not a chance would I do that!'},
        {id: 79, questions_Id: 21, response: '3', correct: 'no', description: 'Incorrect.'},
        {id: 80, questions_Id: 21, response: '2', correct: 'no', description: 'Nope.'},
        {id: 81, questions_Id: 21, response: '1', correct: 'no', description: 'Nah, but getting closer.'},
        {id: 82, questions_Id: 21, response: '0', correct: 'yes', description: 'Correct. My feet are tough as nails...I know this last question was lame but I can not think of a better one.'},
        {id: 83, questions_Id: 22, response: '5', correct: 'no', description: 'If only I were so lucky.'},
        {id: 84, questions_Id: 22, response: '1', correct: 'yes', description: 'Yup. I had one warm oatmeal breakfast. Then due to some unfortunate events the camp stove went missing. Which meant a lot of cold canned food...Yummmm.'},
        {id: 85, questions_Id: 22, response: '10', correct: 'no', description: 'Nope.'},
        {id: 86, questions_Id: 22, response: '3', correct: 'no', description: 'Incorrect.'},
        {id: 87, questions_Id: 23, response: 'Yes', correct: 'yes', description: 'Yeah...I have a problem.'},
        {id: 88, questions_Id: 23, response: 'No', correct: 'no', description: 'Nope. I am addicted to the code!'},
        {id: 89, questions_Id: 24, response: 'On the second day of the trip in McDonalds.', correct: 'yes', description: 'Yup. Life can change pretty quick. Day two consisted of chilling in McDonalds and planning out an entirel new trip.'},
        {id: 90, questions_Id: 24, response: 'Weeks in advance.', correct: 'no', description: 'Kind of, but not really. There was a plan set up early on, but that plan did not come to fruition.'},
        {id: 91, questions_Id: 24, response: 'The day before boarding the flight.', correct: 'no', description: 'If you know me, this would be something I would do. But not this time.'},
        {id: 92, questions_Id: 24, response: 'No plan, just winged the whole thing.', correct: 'no', description: 'This would have been fun to try, but it is not what I did.'},
        {id: 93, questions_Id: 25, response: 'Canyon Swing.', correct: 'no', description: 'Nope. I did it, and it was epic!.'},
        {id: 94, questions_Id: 25, response: 'Flying Fox.', correct: 'no', description: 'Nope. Did this too. Not terribly scary but a ton of fun!'},
        {id: 95, questions_Id: 25, response: 'Black Water Rafting.', correct: 'no', description: 'Nope. Did this. It was really cool to see the glow worms. I do not know if the "adventure" is really worth the cost though.'},
        {id: 96, questions_Id: 25, response: 'Bungee Jump.', correct: 'yes', description: 'Correct. I have done a bungee before, so decided to try other things out this time.'},
        {id: 97, questions_Id: 26, response: 'Mount Sunday/Edoras.', correct: 'no', description: 'Uuu, good guess, but not the best experience. I can not explain it, but ever since seeing this place in the LOTR movies, I have always wanted to see it in person. Felt amazing to finally get to do that.'},
        {id: 98, questions_Id: 26, response: 'Puzzling World.', correct: 'no', description: 'A super fun time, but there is still something better. Would totally go here again but would recommend not going solo haha.'},
        {id: 99, questions_Id: 26, response: 'Milford Sound cruise.', correct: 'yes', description: 'Yup! Hands down this is the coolest place I have ever been. Simply jaw dropping.'},
        {id: 100, questions_Id: 26, response: 'Roys Peak to Mount Alpha.', correct: 'no', description: 'Correct. I have done a bungee before, so decided to try other things out this time.'},
        {id: 101, questions_Id: 27, response: '0', correct: 'no', description: 'Gross, I am not that grungy...but I did get pretty fricking grungey.'},
        {id: 102, questions_Id: 27, response: '1', correct: 'no', description: 'Nope. I did only have 1 hot shower though.'},
        {id: 103, questions_Id: 27, response: '2', correct: 'yes', description: 'Yup. And they were waaay too far a long into my trip. A guess that is a bonus of solo travelling. Do not have to appease anyone else.'},
        {id: 104, questions_Id: 27, response: '3', correct: 'no', description: 'No'},
        {id: 105, questions_Id: 28, response: '1', correct: 'no', description: 'Nope'},
        {id: 106, questions_Id: 28, response: '2', correct: 'no', description: 'If the question was how many sites did I know about while I was there, then you would be correct. But that is not the question'},
        {id: 107, questions_Id: 28, response: '3', correct: 'no', description: 'No'},
        {id: 108, questions_Id: 28, response: '4', correct: 'yes', description: 'Yup. I honestly did not know some of these places were LOTR sites until after I left. Mount Sunday (Edoras), Twelve Mile Delta (where Sam sees Oliphants), Lake Te Anau (there are a ton of locations here), Mount Ngauruhoe (Mount Doom)'},
        {id: 109, questions_Id: 29, response: 'Rotorua', correct: 'no', description: 'Nope. Did not go there, so I can not really want to go back there.'},
        {id: 110, questions_Id: 29, response: 'Milford Sound', correct: 'no', description: 'Not quite. This was a tough call. But I want go elsewhere.'},
        {id: 111, questions_Id: 29, response: 'Wanaka', correct: 'yes', description: 'Nailed it! I barely spent anytime in Wanaka, but it seems like the perfect place. There is a gorgeous lake, it is surrounded by mountains, there are hikes minutes from town, and ski resorts as well. Not to mention it is was less busy then Queenstown.'},
        {id: 112, questions_Id: 29, response: 'Wellington', correct: 'no', description: 'Nah. If I get tickets to an All Blacks came there, then yes. Bonus points if you buy me tickets...and come with me haha.'},
        {id: 113, questions_Id: 30, response: '3 days', correct: 'no', description: 'Hmm, that would be some crazy driving to make it from Queenstown to Auckland in 3 days. But It could be done. I did not do it though.'},
        {id: 114, questions_Id: 30, response: '17 days', correct: 'no', description: 'Nope'},
        {id: 115, questions_Id: 30, response: '22 days', correct: 'no', description: 'I wish it was this long.'},
        {id: 116, questions_Id: 30, response: '13 days', correct: 'yes', description: 'Correct. Short and sweet but I crammed a lot in so it is quite the trip.'},
        {id: 117, questions_Id: 31, response: 'Winnies Pizza', correct: 'yes', description: 'Chyea. I love pizza and this one was great! Had some home made sour cream/cream cheese topping, just epic.'},
        {id: 118, questions_Id: 31, response: 'Ferburger', correct: 'no', description: 'Nah. It was a good burger. But it nothing too amazing'},
        {id: 119, questions_Id: 31, response: 'McDonalds', correct: 'no', description: 'No, but I did eat here more than I would like to admit.'},
        {id: 120, questions_Id: 31, response: 'Watties canned pasta', correct: 'no', description: 'Dang that would be sad if this was the correct answer. I did eat it a few times, and thankfully I had a few better meals a long the way.'},
        {id: 121, questions_Id: 32, response: 'West Coast of the South Island', correct: 'no', description: 'Nah'},
        {id: 122, questions_Id: 32, response: 'West Coast of the North Island', correct: 'no', description: 'No'},
        {id: 123, questions_Id: 32, response: 'East Coast of the South Island', correct: 'yes', description: 'Yup. I enjoyed a nice cold can of Stagg Chili on these rocks, somewhere between Christchurch and Picton.'},
        {id: 124, questions_Id: 32, response: 'East Coast of the North Island', correct: 'no', description: 'Nope'},
        {id: 125, questions_Id: 33, response: 'Ben Lomond/Queenstown', correct: 'no', description: 'Nope Queenstown wasn\'t quite this gorgeous'},
        {id: 126, questions_Id: 33, response: 'Roys Peak/Wanaka', correct: 'yes', description: 'Yup! Take me back! This place was amazing!'},
        {id: 127, questions_Id: 33, response: 'Queenstown Hill/Queenstown', correct: 'no', description: 'Nah, the views from Queenstown Hill are nothing like this'},
        {id: 128, questions_Id: 33, response: 'Milford Sound', correct: 'no', description: 'Nope. Milford Sound might be more epic then this place'},
        {id: 129, questions_Id: 34, response: 'Milford Sound', correct: 'yes', description: 'Correct. I guess this pic could be any of the above, but this is the only place I visited'},
        {id: 130, questions_Id: 34, response: 'Queen Charlotte Sound', correct: 'no', description: 'Nope. I did not make it here'},
        {id: 131, questions_Id: 34, response: 'Marlborough Sounds', correct: 'no', description: 'Nah. Did not go here'},
        {id: 132, questions_Id: 34, response: 'Doubtful Sound', correct: 'no', description: 'No. Did not make my way here either'},
        {id: 133, questions_Id: 35, response: 'Mount Sunday', correct: 'no', description: 'Nah, this is not Middle Earth.'},
        {id: 134, questions_Id: 35, response: 'Tongariro Alpine Crossing', correct: 'no', description: 'Nope. It was so damn foggy on the crossing that I did not see anything.'},
        {id: 135, questions_Id: 35, response: 'Ben Lomond', correct: 'no', description: 'Nope.'},
        {id: 136, questions_Id: 35, response: 'Mount Alpha', correct: 'no', description: 'Yup. Geology Rocks! haha punny'},
        {id: 137, questions_Id: 36, response: 'Mt Doom', correct: 'no', description: 'Nah. I feel so sorry for you if you think this Mont Doom.'},
        {id: 138, questions_Id: 36, response: 'The Shire', correct: 'no', description: 'Nope. It is green like the shire but that is it'},
        {id: 139, questions_Id: 36, response: 'Edoras', correct: 'yes', description: 'Nailed it! This place is dope, and I was so happy to visit it.'},
        {id: 140, questions_Id: 36, response: 'Mines of Moria', correct: 'no', description: 'Nah. Mines are undergound...this is above ground...'},
        {id: 141, questions_Id: 37, response: 'Rocks', correct: 'no', description: 'Well yeah, but no. Need more specifics'},
        {id: 142, questions_Id: 37, response: 'Alluvial Fan', correct: 'yes', description: 'Woohoo, you are basically geologist now.'},
        {id: 143, questions_Id: 37, response: 'Rock Slide', correct: 'no', description: 'Kind of not really. So no.'},
        {id: 144, questions_Id: 37, response: 'Glacier', correct: 'no', description: 'Not even close.'},
        {id: 145, questions_Id: 38, response: 'Drive to Milford Sound.', correct: 'yes', description: 'Yup! I was losing my mind on this drive. It was unreal! So many waterfalls, and so little time...I actually missed my cruise of Milford Sound because I stopped too many times. Got on the next sailing though. So all good.'},
        {id: 146, questions_Id: 38, response: 'Arthus Pass', correct: 'no', description: 'Nope. Beautiful drive though.'},
        {id: 147, questions_Id: 38, response: 'Tongariro National Park', correct: 'no', description: 'Nah. That drive was meh.'},
        {id: 148, questions_Id: 38, response: 'Road to Piha', correct: 'no', description: 'Nope. Still haven\'t been here.'},
        {id: 149, questions_Id: 39, response: 'Mars.', correct: 'no', description: 'No. But nice try. I kind of thought I was on Mars'},
        {id: 150, questions_Id: 39, response: 'Mount Fox', correct: 'no', description: 'Nope. It was foggy on Mount Fox too, but that is about it.'},
        {id: 151, questions_Id: 39, response: 'Tongariro Alpine Crossing', correct: 'yes', description: 'Yup. Sucked that I could not see a thing. But also very cool atmosphere. Very eerie and off worldly.'},
        {id: 152, questions_Id: 39, response: 'Ben Lomond', correct: 'no', description: 'Nah. It was nothing but clear skies up on Ben Lomond'}
      ])
    })
}
